import {galleryDb,galleryBucket,config} from '@/lib/gallery-db';
export const dynamic='force-dynamic';
type Photo={id:string;name:string;key:string;size:number;type:string;position:number;folder_id:string|null};
type Folder={id:string;name:string;position:number};
const sha=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
function responseHeaders(req:Request){const origin=req.headers.get('Origin');const own=config().PUBLIC_ORIGIN||new URL(req.url).origin;const h=new Headers({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Vary':'Origin'});if(origin&&(origin===config().ALLOWED_ORIGIN||origin===own)){h.set('Access-Control-Allow-Origin',origin);h.set('Access-Control-Allow-Headers','Authorization, Content-Type');h.set('Access-Control-Allow-Methods','GET, POST, OPTIONS')}return h}
function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:responseHeaders(req)})}
export async function OPTIONS(req:Request){return new Response(null,{status:204,headers:responseHeaders(req)})}
export async function GET(req:Request){try{const db=galleryDb();const url=new URL(req.url);if(url.searchParams.get('action')==='image'){const p=await db.prepare('SELECT * FROM photos WHERE id=?').bind(url.searchParams.get('id')).first<Photo>();if(!p)throw new Problem('Photo introuvable.',404);const obj=await galleryBucket().get(p.key);if(!obj)throw new Problem('Photo introuvable.',404);const h=responseHeaders(req);h.set('Content-Type',p.type);h.set('Content-Length',String(obj.size));h.set('Cache-Control','public, max-age=31536000, immutable');return new Response(obj.body,{headers:h})}const [photoRows,folderRows,initialized]=await Promise.all([db.prepare('SELECT * FROM photos ORDER BY position, id').all<Photo>(),db.prepare('SELECT * FROM folders ORDER BY position, id').all<Folder>(),db.prepare("SELECT value FROM settings WHERE key='initialized'").first()]);const origin=config().PUBLIC_ORIGIN||url.origin;return json(req,{initialized:!!initialized,folders:folderRows.results,photos:photoRows.results.map((p:Photo)=>({id:p.id,name:p.name,type:p.type,size:p.size,folderId:p.folder_id,url:origin+'/api/gallery?action=image&id='+encodeURIComponent(p.id)+'&v='+encodeURIComponent(p.key)}))})}catch(e){console.error('gallery-read',e);return json(req,{error:e instanceof Problem?e.message:'Les photos sont momentanément indisponibles.'},e instanceof Problem?e.status:503)}}
async function bounded(req:Request,max:number){const reader=req.body?.getReader();if(!reader)throw new Problem('Requête vide.');const chunks:Uint8Array[]=[];let total=0;while(true){const {value,done}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){await reader.cancel();throw new Problem('Fichier trop volumineux (20 Mo maximum).',413)}chunks.push(value)}const data=new Uint8Array(total);let offset=0;for(const c of chunks){data.set(c,offset);offset+=c.length}return new Request(req.url,{method:'POST',headers:req.headers,body:data})}
function cleanName(value:unknown){if(typeof value!=='string')throw new Problem('Nom invalide.');const name=value.replace(/[\x00-\x1f]/g,'').trim().slice(0,80);if(!name)throw new Problem('Donnez un nom au dossier.');return name}
async function validFolder(db:D1Database,value:unknown){if(value===null||value===''||value===undefined)return null;if(typeof value!=='string')throw new Problem('Dossier invalide.');if(!await db.prepare('SELECT id FROM folders WHERE id=?').bind(value).first())throw new Problem('Ce dossier n’existe plus.',409);return value}
export async function POST(original:Request){try{const db=galleryDb();const action=new URL(original.url).searchParams.get('action');const origin=original.headers.get('Origin');if(origin&&origin!==config().ALLOWED_ORIGIN&&origin!==(config().PUBLIC_ORIGIN||new URL(original.url).origin))throw new Problem('Origine non autorisée.',403);
if(action==='login'){if(!config().ADMIN_CODE)throw new Problem('L’accès administrateur n’est pas configuré.',503);const now=Date.now(),ip=original.headers.get('cf-connecting-ip')||'unknown',key=await sha(ip+':'+Math.floor(now/900000));const attempt=await db.prepare('INSERT INTO attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+900000).first<{count:number}>();if(!attempt||attempt.count>10)throw new Problem('Trop de tentatives. Réessayez dans 15 minutes.',429);const req=await bounded(original,4096);const {code}=await req.json() as {code?:string};if(typeof code!=='string'||code.length>256||await sha(code)!==await sha(config().ADMIN_CODE!))throw new Problem('Code incorrect.',401);const token=crypto.randomUUID()+crypto.randomUUID();await db.batch([db.prepare('DELETE FROM sessions WHERE expires<?').bind(now),db.prepare('DELETE FROM attempts WHERE expires<?').bind(now),db.prepare('INSERT INTO sessions(hash,expires) VALUES(?,?)').bind(await sha(token),now+12*3600000)]);return json(original,{token})}
const auth=original.headers.get('Authorization')||'';if(!auth.startsWith('Bearer ')||auth.length>200)throw new Problem('Reconnectez-vous pour continuer.',401);const hash=await sha(auth.slice(7));if(!await db.prepare('SELECT hash FROM sessions WHERE hash=? AND expires>?').bind(hash,Date.now()).first())throw new Problem('Reconnectez-vous pour continuer.',401);if(action==='logout'){await db.prepare('DELETE FROM sessions WHERE hash=?').bind(hash).run();return json(original,{ok:true})}
const req=await bounded(original,action==='upload'||action==='replace'?20*1024*1024+65536:65536);
if(action==='upload'||action==='replace'){const data=await req.formData(),file=data.get('file');if(!(file instanceof File)||file.size===0||file.size>20*1024*1024)throw new Problem('Choisissez une photo de moins de 20 Mo.');const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());let type='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)type='image/jpeg';if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10)type='image/png';if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')type='image/webp';if(!type||type!==file.type)throw new Problem('Format invalide. Utilisez JPG, PNG ou WebP.');const folderId=await validFolder(db,data.get('folderId'));let old:Photo|null=null;const id=action==='replace'?String(data.get('id')):crypto.randomUUID();if(action==='replace'){old=await db.prepare('SELECT * FROM photos WHERE id=?').bind(id).first<Photo>();if(!old)throw new Problem('Cette photo a déjà été supprimée.',404)}else{const count=await db.prepare('SELECT COUNT(*) AS n FROM photos').first<{n:number}>();if((count?.n||0)>=500)throw new Problem('Cet album peut contenir jusqu’à 500 photos.')}const key='photos/'+crypto.randomUUID();await galleryBucket().put(key,file.stream(),{httpMetadata:{contentType:type}});const name=file.name.replace(/[\x00-\x1f]/g,'').slice(0,180)||'Photo';try{if(old){const result=await db.prepare('UPDATE photos SET name=?,key=?,type=?,size=? WHERE id=? AND key=?').bind(name,key,type,file.size,id,old.key).run();if(!result.meta.changes)throw new Problem('La photo a été modifiée. Rechargez l’album.',409)}else await db.batch([db.prepare('INSERT INTO photos(id,name,key,type,size,position,folder_id) SELECT ?,?,?,?,?,COALESCE(MAX(position),-1)+1,? FROM photos WHERE folder_id IS ?').bind(id,name,key,type,file.size,folderId,folderId),db.prepare("INSERT INTO settings(key,value) VALUES('initialized','1') ON CONFLICT(key) DO UPDATE SET value='1'")])}catch(e){await galleryBucket().delete(key);throw e}if(old){try{await galleryBucket().delete(old.key)}catch(e){console.error('old-file-cleanup',e)}}return json(original,{ok:true,id})}
const data=await req.json() as {id?:string;ids?:string[];name?:string;folderId?:string|null};
if(action==='folder-create'){const name=cleanName(data.name);const count=await db.prepare('SELECT COUNT(*) AS n FROM folders').first<{n:number}>();if((count?.n||0)>=100)throw new Problem('Cet album peut contenir jusqu’à 100 dossiers.');const id=crypto.randomUUID();await db.prepare('INSERT INTO folders(id,name,position) SELECT ?,?,COALESCE(MAX(position),-1)+1 FROM folders').bind(id,name).run();return json(original,{ok:true,id})}
if(action==='folder-rename'){const name=cleanName(data.name);const result=await db.prepare('UPDATE folders SET name=? WHERE id=?').bind(name,data.id).run();if(!result.meta.changes)throw new Problem('Ce dossier n’existe plus.',404);return json(original,{ok:true})}
if(action==='folder-delete'){if(typeof data.id!=='string')throw new Problem('Dossier invalide.');await db.batch([db.prepare('UPDATE photos SET folder_id=NULL WHERE folder_id=?').bind(data.id),db.prepare('DELETE FROM folders WHERE id=?').bind(data.id)]);return json(original,{ok:true})}
if(action==='folder-reorder'){const ids=data.ids;if(!Array.isArray(ids)||ids.length>100||ids.some(x=>typeof x!=='string')||new Set(ids).size!==ids.length)throw new Problem('Ordre invalide.');const current=await db.prepare('SELECT id FROM folders').all<{id:string}>();if(current.results.length!==ids.length||current.results.some((p:{id:string})=>!ids.includes(p.id)))throw new Problem('Les dossiers ont changé. Rechargez-les.',409);if(ids.length)await db.batch(ids.map((id:string,i:number)=>db.prepare('UPDATE folders SET position=? WHERE id=?').bind(i,id)));return json(original,{ok:true})}
if(action==='photo-folder'){const folderId=await validFolder(db,data.folderId);const result=await db.prepare('UPDATE photos SET folder_id=?,position=(SELECT COALESCE(MAX(position),-1)+1 FROM photos WHERE folder_id IS ?) WHERE id=?').bind(folderId,folderId,data.id).run();if(!result.meta.changes)throw new Problem('Photo introuvable.',404);return json(original,{ok:true})}
if(action==='delete'){if(typeof data.id!=='string')throw new Problem('Photo invalide.');const old=await db.prepare('SELECT * FROM photos WHERE id=?').bind(data.id).first<Photo>();if(old){await db.prepare('DELETE FROM photos WHERE id=?').bind(data.id).run();try{await galleryBucket().delete(old.key)}catch(e){console.error('deleted-file-cleanup',e)}}return json(original,{ok:true})}
if(action==='reorder'){const ids=data.ids,folderId=await validFolder(db,data.folderId);if(!Array.isArray(ids)||ids.length>500||ids.some(x=>typeof x!=='string')||new Set(ids).size!==ids.length)throw new Problem('Ordre invalide.');const current=await db.prepare('SELECT id FROM photos WHERE folder_id IS ?').bind(folderId).all<{id:string}>();if(current.results.length!==ids.length||current.results.some((p:{id:string})=>!ids.includes(p.id)))throw new Problem('L’album a changé. Rechargez-le avant de réorganiser.',409);if(ids.length)await db.batch(ids.map((id:string,i:number)=>db.prepare('UPDATE photos SET position=? WHERE id=?').bind(i,id)));return json(original,{ok:true})}throw new Problem('Action inconnue.',404)
}catch(e){console.error('gallery-write',e instanceof Problem?e.message:e);return json(original,{error:e instanceof Problem?e.message:'L’enregistrement a échoué. Vos fichiers restent sur votre appareil, vous pouvez réessayer.'},e instanceof Problem?e.status:503)}}
